version: "3"

services:
  strem-io:
    image: stremio/server:latest
    ports:
      - "11470:11470"
    restart: always
    volumes:
      - "./data:/root/.stremio-server"
    environment:
      - NO_CORS=1

  app:
    build: .
    # ports:
    # - "9000:8080"
    expose:
      - 8080
    depends_on:
      - strem-io

  nginx:
    build:
      context: .
      dockerfile: ./NginxDockerfile
    restart: always # or "always"
    volumes:
      # - ./web.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9002:443"
    depends_on:
      - app
